import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

import { Gabarito, Nunito } from 'next/font/google'

const gabarito = Gabarito({
  subsets: ['latin'],
  weight: ['400', '700', '900'], // Adjust weights as needed
  display: 'swap',
})

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['200', '400', '700', '900', '1000'], // Customize as needed
  style: ['normal', 'italic'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "BingeWhat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gabarito.className} ${nunito.className} bg-[#051f29] text-[#3cd293]`}>
        <Header />
        <main className="relative mx-auto ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
